default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: guts-dev

test:
  <<: *default
  database: guts-test

production:
  <<: *default
  database: guts
